### ISSUE TITLE
Question about percents

### ISSUE THREAD

**Issue by AnthonyH45** [ledelaney/biol002#1]
In chapter 1 (https://github.com/ledelaney/biol002/blob/main/01-birth.Rmd#L19), we see
`represents only five percent of the matter contained in the universe. We know the most about this kind of matter, because, well, we can see it, and touch it, and also we _are_ it. Yet nearly 85 percent of the matter in the universe`

Should `85%` be `95%` or is the `five percent` in the previous line the part that is incorrect?

**Comment by ledelaney** [comment]
Wow, thank you for our first issue! 🥲 

Going off of [this website](https://map.gsfc.nasa.gov/universe/uni_matter.html), we have about 5% ordinary matter (atoms, like we discussed in lecture 2), 24% dark matter, and 71% dark energy. So, I will update this piece of the textbook because the math is weird and unclear and also kinda wrong. LOL, good catch.
